---
- name: Configure host.
  hosts: all

  pre_tasks:
    - name: Install nfs-common
      ansible.builtin.apt:
        name: nfs-common
        state: present
      become: true

    - name: Install snapd
      ansible.builtin.apt:
        name: snapd
        state: present
      become: true

    - name: Mount TV Share
      ansible.posix.mount:
        src: nas-host.fitzy.foo:/share/TV
        path: /mnt/TV
        opts: rw,sync,hard
        state: mounted
        fstype: nfs
      become: true
    
    - name: Mount Movies Share
      ansible.posix.mount:
        src: nas-host.fitzy.foo:/share/Movies
        path: /mnt/Movies
        opts: rw,sync,hard
        state: mounted
        fstype: nfs
      become: true

  roles:
      - name: jonakoudijs.plex
        become: true